SELECT res2.customerid FROM 
(SELECT  res.customerid, count(res.genreid) AS genreCtr FROM
	(SELECT DISTINCT C.CUSTOMERID, T.GENREID FROM TRACK AS T
		JOIN INVOICELINE IL ON IL.TRACKID = T.TRACKID
		JOIN INVOICE I ON I.INVOICEID = IL.INVOICEID
		JOIN CUSTOMER C ON C.CUSTOMERID = I.CUSTOMERID
	  WHERE T.GENREID IN (	SELECT DISTINCT G.GENREID 
							FROM GENRE G
							WHERE G.NAME LIKE 'S%')) as res
GROUP BY res.customerid) AS res2
WHERE res2.genreCtr = (SELECT count(*) FROM genre WHERE NAME LIKE'S%')